### PR TITLE
Dynamically fetch ECR URL

### PR DESCRIPTION
**Pull request by PiotrNowicki**
Add a routine to initialize custom repository mapping dynamically (using alias URL proxy and its Www-Authenticate header from ECR).

### CODE REVIEW

**Comment by PiotrNowicki** [comment]
Hi @amancevice - please let me know what you think about this extension.

I am currently using custom URL for those ugly AWS ECR URL's. The missing piece was the ECR Credentials Helper and your script works like a charm.

I was looking for something that I can dynamically refresh (in case the proxy / alias / custom domain would repoint to other location). Hence thought of this  `initDynamic` that might be called at the init and possibly using some scheduled job to keep it up to date.

Another solution would be to refresh the value on `get` method, however I didn't want to make it more obfuscated - I like the cleanness of it right now :-)

Thanks for the great work!

**Comment by amancevice** [comment]
this seems like a good feature but I'm not crazy about the entrypoint, `initDynamic` — I think maybe a better interface would be to make `init` aware of stdin being open and reading from there. eg:

```bash
docker-credential-ecr-custom init               # reads config from prompt input
my-command | docker-credential-ecr-custom init  # reads config from stdin
```

**Comment by PiotrNowicki** [comment]
Thanks for the suggestion - that makes perfect sense - please take a look at the current state and let me know what you think.

**Comment by amancevice** [comment]
Sorry for the delay here — had some business come up over the weekend. 

Upon reflection this feels a little too opinionated to me — users would have to set up their deployment to work a specific way (as you probably have) that isn't something out-of-the-box.

Maybe a better solution for you is to write a script that generates the config file dynamically with cron or whatever. All that needs to happen is for the file at `~/.ecr/custom.json` (or wherever is set by the `AWS_ECR_CUSTOM_CONFIG` ENV var) to reflect which registry the alias is pointing to.

The least opinionated way to make this work with the `init` subcommand would be to have it expect the pre-generated config on STDIN and write it to the defined config location (as outlined above).

Does that make sense?

**Comment by PiotrNowicki** [comment]
Hi - no prob mate. 

Got your point - feel free to close this MR then. Currently I am using it on my own and it suits my needs, so my goal is achieved; just imagined somebody else might also find it useful - hence the MR. 

However, I totally understand that creating a proxy to ECR is not something very common everybody does, so I'll keep the details on my blog and no need to push it to the original script.

Cheers!

**Comment by amancevice** [comment]
I appreciate your input! Happy pushing/pulling :)

**Pull request closed without merging**
